services:
  anytype-cli:
    build:
      context: .
      args:
        ANYTYPE_CLI_VERSION: v0.1.9
    ports:
      - "31012:31012"
    volumes:
      - anytype-data:/home/anytype/.anytype
      - ../files/network.yml:/home/anytype/.config/anytype/network.yml:ro
    command: ["serve", "--listen-address", "0.0.0.0:31012"]
    restart: unless-stopped
volumes:
  anytype-data:
